Feature/pc 192 matching main UI
YAPP-Github/Piece-iOS pull request #6
Opened 2024-12-31 11:52 UTC by agseou

## 🏷️ 티켓 번호
[PC-192](https://yapp25app3.atlassian.net/browse/PC-192)

## 👷🏼‍♂️ 변경 사항
- `MatchingAnswer` 컴포넌트 생성
- `RoundedButton`에 Height에 대한 parameter 추가
-  임시 피쳐인 `Home`을  `MatchingMain`으로 변경
- `MatchingMain` 모듈에 `Design System` 의존성 추가
 
## 💬 참고 사항
- `MatchingAnswer` 컴포넌트를 오픈 전, 응답대기중, 응답완료, 매칭완료, 그린라이트 5가지 상태에 대해 enum으로 나누어 타입을 지정하는 방식이예요!

    ```swift

    public enum MatchingStatus {
        case before // 오픈 전
        case waiting // 응답대기중
        case done // 응답완료
        case complete // 매칭완료
        case green_light // 그린라이트
    }
    ```
- 임시이던 `Home`을 `MatchingMain`으로 바꿔두었는데 이름이 적절한가 의문이 드네요 🥲🥲 의견 부탁드립니당 ㅎㅎ

## 📸 스크린샷(Optional)

| MatchingAnswer | Matching Main View |
| :--: | :--: |
| <img width="375" alt="MatchingAnswer" src="https://github.com/user-attachments/assets/253d2ec6-a92b-4ff3-85a7-af855b1fb685"> | <img width="375" alt="Matching Main View" src="https://github.com/user-attachments/assets/b6340c57-d3bb-44a0-a160-9b13b6271a08"> |

2025-01-02 13:05 UTC, dev-summer requested changes

2025-01-02 13:05 UTC, dev-summer commented on Presentation/Feature/MatchingMain/Sources/MatchingMainView.swift
> +  public var body: some View {
navigation이나 router 같은거 고민하면서 꼭 Public이어야 하는지 검토해봐야 할 것 같아요.
저도 제가 추천드렸던 `swift-navigation`인가? 이걸 아직 써본 건 아닌데 SwiftUI 오픈톡방같은데서 저거 사용해보는 걸 추천하시더라구요. 우선 internal로 변경하고 저거 적용하면서 public으로 바뀌어야 할 지 고민해보는 건 어떨까요?

2025-01-02 13:05 UTC, dev-summer commented on Presentation/Feature/MatchingMain/Sources/MatchingMainView.swift
> +        }
피그마에 보면 태그들 전부 보여준 다음에 빈 뷰 높이 32Pt짜리 넣어달라고 요구사항 있었던 것 같은데(코멘트로) 확인 해주세요~

2025-01-02 13:05 UTC, dev-summer commented on Presentation/Feature/MatchingMain/Sources/MatchingMainView.swift
> +    }
여기도 하드코딩보다는 어떻게 상위뷰에서 정보 받아올지 미리 고민해서 수정해주시면 좋을 것 같습니다!

2025-01-02 13:13 UTC, dev-summer commented on Presentation/Feature/MatchingMain/Project.swift
> +)
제가 `dynamic`이랑 `static`으로 구분해서 만들어 둔 이유는, 여러 모듈에서 참조하지 않는(하나의 모듈에서만 참조하는) 모듈의 경우 `static`으로 했을 때 앱 성능을 좀 더 개선할 수 있기 때문이에요.
각 피처 모듈의 경우는 1개의 라우터 역할을 하는 모듈 또는 앱 메인 모듈에서만 참조할 것이라고 예상이 되어서(그리고 그런 구조가 이상적이라고 생각해서) `static`으로 하는 건 어떨까요?

2025-01-02 13:49 UTC, dev-summer commented on Presentation/Feature/MatchingMain/Sources/MatchingMainView.swift
> +      Text("남았어요")
타이머도 타이머 돌려서 뷰에서 시간 넘어가는것까지 구현해주세요~

2025-01-03 05:45 UTC, agseou commented on Presentation/Feature/MatchingMain/Sources/MatchingMainView.swift
> +        }
앗 놓치고 있었네요! 꼼꼼히 봐주셔서 감사합니다!

2025-01-03 05:48 UTC, agseou commented on Presentation/Feature/MatchingMain/Project.swift
> +)
아핫! dynamic이랑 static의 구분에 대해 완전히 잘못알고 있었네요...🥲
자세한 설명 감사합니다! 좀 더 참고자료 찾아보구 공부해야겠어요..ㅎㅎ
static으로 바꾸어 반영해두겠습니다!

2025-01-06 06:01 UTC, agseou commented on Presentation/Feature/MatchingMain/Sources/MatchingMainView.swift
> +  public var body: some View {
넵 좋습니다! `swift-navigation` 사용에 대해 공부해보고 고민해보겠습니다

2025-01-06 08:44 UTC, agseou commented on Presentation/Feature/MatchingMain/Sources/MatchingMainView.swift
> +      Text("남았어요")
넵! 따로 TimerViewModel을 생성해서 분리하겠습니다! 시간에 따른 DateFormatter+Extesion을 생성했는데 따로 Extension을 모아둘 모듈을 두는 건 어떨까요?

2025-01-06 14:56 UTC, dev-summer commented on Presentation/Feature/MatchingMain/Sources/MatchingMainView.swift
> +      Text("남았어요")
넵 `Foundation`의 타입들을 extension한 모듈 만드는 것 좋다고 생각합니다👍🏻 저도 필요해서 만드려고 했었어요!

2025-01-06 14:57 UTC, dev-summer commented
이거 일단은 `@ObservableObject`로 가시는 걸까용?? 혹시나 `@Observable`로 수정하여 다시 커밋 예정이시면 알려주세요.
확인해주시면 리뷰하도록 하겠습니다!

2025-01-07 08:39 UTC, agseou commented
`@Observable` 구조 확정인지 잘 모르겠어서, 일단은 `@ObservableObject`로 해두었습니당!!
`@Observable`로 확정인거 같으니 변경 후 다시 리뷰 요청드릴게요 ☺️

2025-01-07 11:30 UTC, dev-summer requested changes
타이머 잘 동작하는지 확인하려고 했는데 프로젝트가 안 켜져서 확인을 못했어요. 우선 코멘트 내용 확인하시고 다시 리뷰 요청주시면 그때 또 확인해볼게요.

2025-01-07 11:30 UTC, dev-summer commented on Presentation/Feature/MatchingMain/Sources/MatchingAnswer.swift
> +  ) {
parameter가 1개인 경우에는 굳이 개행 할 필요는 없을 것 같습니다~

2025-01-07 11:30 UTC, dev-summer commented on Presentation/Feature/MatchingMain/Sources/MatchingMainViewModel.swift
> +        ]
이건 왜 있는 건가요? 굳이 필요 없는 상수인 것 같은데요.
화면을 그려보고 싶은 거라면 프리뷰에서만 할당해서 확인하면 될 것 같은데요.

2025-01-07 11:30 UTC, dev-summer commented on Presentation/Feature/MatchingMain/Sources/MatchingMainViewModel.swift
> +        case fetchProfile
이것도 뷰에서 호출 안 하는 액션인 것 같은데 왜 있는건가요?

2025-01-07 11:30 UTC, dev-summer commented on Tuist/ProjectDescriptionHelpers/Modules.swift
> +    case Extension
그냥 Extension 보다는 `PCFoundationExtension` 이런식으로 이름을 명확하게 해 주면 좋을 것 같아요

2025-01-07 11:30 UTC, dev-summer commented on Presentation/Feature/MatchingMain/Sources/MatchingTimerViewModel.swift
> +    return calendar.date(from: targetDateComponents)!
force unwrapping 안됩니다잉

2025-01-07 11:30 UTC, dev-summer commented on Presentation/Feature/MatchingMain/Sources/MatchingProfileCardView.swift
> +}
타입 자체를 분리해서 작성하실 거라면, 가독성 높이기 위해서 별도 파일로 분리했을 것 같아요.

2025-01-07 11:30 UTC, dev-summer commented on Presentation/Feature/MatchingMain/Sources/MatchingProfileCardView.swift
> +}
추가로 고민인 점은, 사실 이 영역이 시각적으로 버튼의 형태는 아니잖아요? 그래서 버튼이라는 네이밍이 적절한가 하는 고민이 있어요.

2025-01-07 11:30 UTC, dev-summer commented on Utility/Extension/Project.swift
> +)
`dynamicResourceFramework`로 만드시면 `Resources` 디렉토리가 있어야 해요.
그리고 이 모듈에서는 `Resources` 폴더가 아마 필요하지 않을 것 같습니다.
tuist generate 해보시면 프로젝트 안 켜질거예요.

2025-01-08 02:34 UTC, agseou commented on Presentation/Feature/MatchingMain/Sources/MatchingMainViewModel.swift
> +        case fetchProfile
추후 서버에서 api 받아오면서 쓰일까 생각해서 두었습니다!

2025-01-08 02:34 UTC, agseou commented on Tuist/ProjectDescriptionHelpers/Modules.swift
> +    case Extension
아핫! 네이밍 변경해서 반영하겠습니다

2025-01-08 02:34 UTC, agseou commented on Presentation/Feature/MatchingMain/Sources/MatchingTimerViewModel.swift
> +    return calendar.date(from: targetDateComponents)!
넷! 주의하겠습니다!

2025-01-08 03:04 UTC, agseou commented on Utility/Extension/Project.swift
> +)
헉! `Resources` 폴더가 비어있어서 깃허브 레포지토리에 안올라갔나봐요ㅠㅠ
수정해놓겠습니다!!

2025-01-08 07:26 UTC, agseou commented on Presentation/Feature/MatchingMain/Sources/MatchingProfileCardView.swift
> +}
시각적으로는 버튼이 아닌 뷰니까 Button이 아닌 View로 끝나게 네이밍 변경하겠습니다!
가독성 측면에서 좀더 고려해서 코드 작성하도록 하겠습니다! 감사합니다!

2025-01-08 08:37 UTC, agseou commented
지영님! 오늘 코드를 고쳐보면서 정말 많이든 생각인데요. 제가 짠 구조를 기반으로는 과도한 파일분리가 오히려 더 코드와 로직을 복잡하게 하는거 같아요.... 내부에서 private computed property로 관리하는 방식으로 고쳐서 재요청드리겠습니다!

2025-01-08 14:59 UTC, agseou commented on Presentation/Feature/MatchingMain/Sources/MatchingMainViewModel.swift
> +        ]
전체적으로 뷰, 뷰모델 구조 개선하면서 옮겨두었습니다!

2025-01-08 14:59 UTC, agseou commented on Presentation/Feature/MatchingMain/Sources/MatchingMainViewModel.swift
> +        case fetchProfile
이것도 전체적으로 뷰, 뷰모델 구조 개선하면서 옮겨두었습니다!

2025-01-09 03:27 UTC, dev-summer requested changes

2025-01-09 03:27 UTC, dev-summer commented on Presentation/Feature/MatchingMain/Sources/MatchingMainView.swift
> +  private var ProfileInfo: some View {
type -> property 변경하시면서 제일 첫번째 글자 대문자 -> 소문자로 변경하는 걸 일괄적으로 빠뜨리신 것 같아요. 수정 부탁드립니다~

2025-01-09 03:27 UTC, dev-summer commented on Utility/PCFoundationExtension/Resources.swift
> +import Foundation
제가 `FoundationExtension` 모듈에 `Resources`가 필요하지 않을 것 같다고 코멘트를 남겼었는데요.
한번 생각해보시면 좋을 것 같습니다.
지금 이 빈 파일은.. 존재할 가치가 없는 파일이잖아요? 단지 디렉토리를 만들기 위해서만 존재하는..
그러면 애초에 `FoundationExtension` 모듈에는 `Resources`가 필요 없는 거 아닐까요?

2025-01-09 03:27 UTC, dev-summer commented on Presentation/Feature/MatchingMain/Sources/MatchingMainView.swift
> +  private var ProfileInfo: some View {
이거 말고 다른것도 마찬가지입니다!

2025-01-09 03:27 UTC, dev-summer commented on Presentation/Feature/MatchingMain/Sources/MatchingMainView.swift
> +  private var SummitButton: some View {
버튼 이름 변경 필요할 것 같아요.
피그마에는 submit이라고 되어 있는데, 실제로 하는 일이 총 4가지나 되서 조금 더 고민해보셔야 할 것 같습니다.
<img width="492" alt="image" src="https://github.com/user-attachments/assets/8221befa-7f8a-42a4-9753-02ee5f8130f3" />

매칭 상태에 따라 버튼 탭 시 액션이 바뀌는데, 이걸 버튼을 여러개를 만들어서 처리할지 아니면 뷰모델에서 로직을 갈라서 처리할지에 따라 달라지겠네용

2025-01-09 03:27 UTC, dev-summer commented on Utility/PCFoundationExtension/Resources.swift
> +import Foundation
그리고 이 파일이 `Utility/PCFoundationExtension/Resources` 디렉토리 내에 들어있는 게 아니라, 그냥 `Utility/PCFoundatinoExtension/Resources.swift`라서 여전히 tuist generate 안됩니다....

2025-01-10 03:22 UTC, agseou commented on Utility/PCFoundationExtension/Resources.swift
> +import Foundation
삭제 후 모듈 dynamicFramework로 변경했습니다!

2025-01-10 03:22 UTC, agseou commented on Presentation/Feature/MatchingMain/Sources/MatchingMainView.swift
> +  private var SummitButton: some View {
matchingButton이라고 바꿨는데 적절한지 아직도 헷갈리네요..ㅠㅠ
4가지 상태에 따라 관리할 수 있도록 Viewmodel 내부에 MatchingButtonState로 4가지 케이스로 관리하도록 했습니다!

2025-01-11 00:13 UTC, dev-summer approved these changes

2025-01-11 00:13 UTC, merged

2025-01-11 00:18 UTC, dev-summer commented on Presentation/Feature/MatchingMain/Sources/MatchingTimerViewModel.swift
> +    targetDateComponents.second = Constant.targetSecond
이거 정책이 뭐 익일 새벽 2시 이렇게 변경될 가능성도 있어서... date까지 포함해서 계산을 하도록 로직을 미리 작성해 두는 것이 좋아보이긴 합니다. 참고해주세용~~~